baseURL: "http://dev.heywilding.com"
title: "projects"
theme: hugo-PaperMod
paginate: 200
pygmentsCodeFences: true
enableInlineShortcodes: true
canonifyURLs: false
relativeURLs: true
pluralizelisttitles: false
refLinksNotFoundURL: "/"
refLinksErrorLevel: "INFO"

languages:
  en:
    languageName: "English"
    weight: 1
    menu:
      main:
        - name: Tags
          url: tags/
          weight: 10
        - name: Categories
          url: categories/
          weight: 10

services:
  instagram:
    disableInlineCSS: true
  twitter:
    disableInlineCSS: true

outputs:
  home:
    - HTML
    - RSS
    - JSON

params:
  imagehost: "https://storage.googleapis.com/mwcw-blog-images"
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  description: "Theme PaperMod - https://github.com/umamiMike/hugo-PaperMod"
  author: Theme PaperMod
  defaultTheme: auto
  # disableThemeToggle: true
  ShowShareButtons: true
  ShowReadingTime: true
  disableSpecial1stPost: true
  displayFullLangName: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowToc: true

  profileMode:
    enabled: true
    title: Profile mode title
    imageUrl: "woman-profile-unsplash.jpg"
    imageTitle: my image
    # imageWidth: 120
    # imageHeight: 120
    buttons:
      - name: Archives
        url: archives
      - name: Tags
        url: tags

  homeInfoParams:
    Title: "Mike Wildings variation on hugoPapermod"
    Content: home info params content 
  socialIcons:
    - name: github
      url: "https://github.com/umamiMike"
    - name: RsS
      url: "index.xml"

  label:
    text: "Home"
    icon: /favicon-32x32.png
    iconHeight: 32

  editPost:
    URL: "https://github.com/umamiMike/projects-and-resources/tree/main/content"
    Text: "Suggest Changes" # edit text
    appendFilePath: true # to append file path to Edit link

markup:
  goldmark:
    renderer:
      unsafe: true

enableEmoji: true

minify:
  disableXML: true


privacy:
  vimeo:
    disabled: false
    simple: true

  twitter:
    disabled: false
    enableDNT: true
    simple: true

  instagram:
    disabled: false
    simple: true

  youtube:
    disabled: false
    privacyEnhanced: true

taxonomies:
  foo: foo
  category: categories
  tag: tags
  bar: bar
